version: 2

sources:
  - name: raw
    database: regal-mediator-483907-t1
    schema: course14
    tables:
      - name: sales
        identifier: gwz_sales
        description: "Sales list in greenweez company"
        columns: 
          - name: date_date
            description: "Date of the order"
            tests:
              - not_null
          - name: products_id
            description: "Id of the product"
            tests:
              - not_null

      - name: customers
        identifier: gwz_customers
        description: "Includes name and surname of the customer"
        columns: 
          - name: id
            description: "unique id of customer"
            tests:
              - unique
              - not_null
          - name: name
            description: "name of the customer"
            tests:
              - not_null